name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # This runs the build script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory that contains the build files
